spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ujjwal-pathak
          searchPaths: ConfigData
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001